name: (reusable) build and push docker image

on:
  workflow_call:
    inputs:
      submodules:
        required: false
        type: boolean
        default: false
      aws_ecr_repository:
        required: false
        type: string
        default: ''
      aws_nonprod_role_arn:
        required: false
        type: string
        default: ''
      aws_prod_role_arn:
        required: false
        type: string
        default: ''
      context:
        required: false
        type: string
        default: .
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      version_build_arg:
        description: 'If it is not empty, then the workflow adds an extra build argument with this input as key and the resolved tag as value'
        required: false
        type: string
        default: ''
    outputs:
      image_tags:
        description: 'Image tags'
        value: ${{ jobs.reusable.outputs.image_tags }}
    secrets:
      bot_private_key:
        required: false
      build_args:
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  reusable:
    runs-on: [self-hosted, linux, x64, bifrost]
    outputs:
      image_tags: ${{ steps.docker-meta.outputs.tags }}
    steps:
      - name: Create Github App token
        if: ${{ inputs.submodules }}
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.CINEMO_PENG_BOT_APP_ID }}
          private-key: ${{ secrets.bot_private_key }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ inputs.submodules && steps.app-token.outputs.token || github.token }}
          submodules: ${{ inputs.submodules && 'recursive' || 'false' }}
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}

      - name: Configure AWS credentials via role
        if: ${{ inputs.aws_ecr_repository != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ (github.ref_type == 'tag' && endsWith(github.ref_name, 'prod')) && inputs.aws_prod_role_arn || inputs.aws_nonprod_role_arn }}

      - name: Extract AWS account ID from role
        if: ${{ inputs.aws_ecr_repository != '' }}
        id: aws-account
        run: |
          role=${{ (github.ref_type == 'tag' && endsWith(github.ref_name, 'prod')) && inputs.aws_prod_role_arn || inputs.aws_nonprod_role_arn }}
          id=${role#*arn:aws:iam::}
          id=${id%%:*}

          echo "id=$id" >> $GITHUB_OUTPUT

      - name: Login to ECR
        if: ${{ inputs.aws_ecr_repository != '' }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ steps.aws-account.outputs.id }}

      - name: Choose tagging strategy
        if: ${{ inputs.aws_ecr_repository != '' }}
        id: tagging-strategy
        run: |
          feat='type=raw,event=pr,value=feat-{{sha}}'
          semver='type=semver,pattern={{raw}}'
          sha='type=sha'

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "strategy=$feat" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "strategy=$semver" >> $GITHUB_OUTPUT
          else
            echo "strategy=$sha" >> $GITHUB_OUTPUT
          fi

      - name: Collect docker metadata
        if: ${{ inputs.aws_ecr_repository != '' }}
        id: docker-meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.aws_ecr_repository }}
          flavor: |
            latest=false
          tags: |
            ${{ steps.tagging-strategy.outputs.strategy }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          push: ${{ inputs.aws_ecr_repository != '' }}
          build-args: |
            ${{ secrets.build_args }}
            ${{ inputs.version_build_arg != '' && format('{0}={1}', inputs.version_build_arg, steps.docker-meta.outputs.version) || '' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
